[package]
name = "benches"
version = "0.0.0"
publish = false
edition = "2021"
license = "MIT"

[features]

[dependencies]

[dev-dependencies]
criterion = "0.5.1"
fastrace = { path = "../fastrace" }
rt-trace = { path = "../rt-trace" }

[[bench]]
name = "compare"
path = "compare.rs"
harness = false
